from django.urls import re_path

from .consumers import GuacamoleWebSocketConsumer

websocket_urlpatterns = [
    re_path(
        # session_id is a UUID generated by lib/cuckoo/core/data/
        # guac_session.py (guac-session-auth patch).  UUIDs
        # contain hyphens (e.g. 4ba0f074-3043-48bf-ab30-c2d285a278eb)
        # which `\w+` does NOT match — `\w` is [A-Za-z0-9_] only.
        # Without the hyphen here the channels router throws
        #   ValueError: No route found for path 'guac/websocket-tunnel/<uuid>'
        # at WebSocket connect time, asgi-server returns HTTP 500,
        # the browser-side Guacamole client sees a closed connection
        # before any guac protocol frame.  Caught on sb deploy
        # 2026-05-24 (ami-0730fe3e5b9fa4817).
        r"^guac/websocket-tunnel/(?P<session_id>[\w-]+)/?$",
        GuacamoleWebSocketConsumer.as_asgi(),
    ),
]
